server:
  port: 8080
  servlet:
    context-path: /api/v1
    session:
      tracking-modes: cookie
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB
      file-size-threshold: 1KB

spring:
  data:
    mongodb:
      uri: mongodb://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:27017/${DB_NAME}?authSource=admin
      auto-index-creation: true

    redis:
      host: ${REDIS_HOST}
      port: 6379
      password: ${REDIS_PASSWORD}
      timeout: 5000ms
      connect-timeout: 2000ms

jwt:
  signer-key: ${JWT_SIGNER_KEY}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}

google:
  api-base-url: ${GG_API_BASE_URL}
  client-id: ${GG_CLIENT_ID}
  client-secret: ${GG_CLIENT_SECRET}
  redirect-url: ${GG_REDIRECT_URI}
  grant-type: ${GG_GRANT_TYPE}
  oauth2-base-url: ${GG_OAUTH2_BASE_URL}

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}
  folder: ${CLOUDINARY_FOLDER}

redis-ttl:
  token-socket-ttl: ${TOKEN_SOCKET_TTL}
  presence-socket-ttl: ${PRESENCE_SOCKET_TTL}

recaptcha:
  verify-url: ${RECAPTCHA_VERIFY_URL}
  cb-secret: ${RECAPTCHA_CB_SECRET}
  inv-secret: ${RECAPTCHA_INV_SECRET}

base:
  fe-url: ${BASE_FE_URL}
  default-avatar-url: ${DEFAULT_AVATAR_URL}

app:
  name: chat
  description: Project Spring Boot website chat
  version: 1.0.0